[basic]kadai1~4
FTS-Yama/javatry pull request #3
Opened 2020-08-20 08:45 UTC by fts-tamori

課題１～４が完了しましたのでレビューをお願いします。

2020-08-20 09:23 UTC, FTS-asato commented on src/test/java/org/docksidestage/javatry/basic/Step01VariableTest.java
> +        Integer land = null;
`final`の付与をお願いします。

2020-08-21 02:17 UTC, FTS-asato requested changes
課題1～4レビュー
全体的に、新規作成する変数、メソッドの引数にはfinalを付与するようにお願いします。
また、章によって最後に自分で問題を考える問題があると思うので、そちらも実施するようにお願いします。

2020-08-21 02:17 UTC, FTS-asato commented on src/test/java/org/docksidestage/javatry/basic/Step02IfForTest.java
> +    // TODO forEachの置き換えがわからないので後回し
TODOコメントは、問題等が解決したのであれば削除するようにお願いします。

2020-08-21 02:17 UTC, FTS-asato commented on src/test/java/org/docksidestage/javatry/basic/Step04MethodTest.java
> +    private String replaceAtoB(String atob) {
引数や変数等の命名はキャメルケースという方式でお願いします。
最初の単語は小文字で、以降の単語の先頭を大文字にする命名規則です。
atob ⇒ aToB

2020-08-21 02:17 UTC, FTS-asato commented on src/test/java/org/docksidestage/javatry/basic/Step04MethodTest.java
> +    }
Stringはimmutableの属性を持つので、replaceを実行しても実際にはatobは書き換えられません。
replaceCtoBメソッドも同様です。

この問題は、最終的には`broadwayBBB`という文言を表示することになるので、
そうするためにはどうしたらよいか考えてみてください。

2020-08-21 02:17 UTC, FTS-asato commented on src/test/java/org/docksidestage/javatry/basic/Step04MethodTest.java
> +        return consolidated;
変数に値を設定する必要はないと思うので、文字列結合した結果をそのまま返すようにお願いします。

2020-08-24 07:04 UTC, FTS-asato requested changes
下記コミットのレビュー
[kadai1-4の指摘対応完了](https://github.com/FTS-Yama/javatry/pull/3/commits/e0b4eebad7619c539d0e9fe268b86a01ff56c7b7)

2020-08-24 07:04 UTC, FTS-asato commented on src/test/java/org/docksidestage/javatry/basic/Step04MethodTest.java
> +    private String replaceAtoB(String aToB) {
引数にfinalの付与をお願いします。
他の作成したメソッドも同様の対応をお願いします。

2020-08-24 08:04 UTC, FTS-asato approved these changes

2020-08-25 01:52 UTC, FTS-Yama commented on src/test/java/org/docksidestage/javatry/basic/Step02IfForTest.java
> +        final List<String> stage2List = new ArrayList<>();
修正は不要ですが、次回からのアドバイスとして記載します。
要素の書き換え（追加や削除）が可能なリストを使用する場合ですが、そのリストが使用できるスコープ（範囲）をなるべく小さくするようにお願いします。

上記のstage2List でいくと「test_iffor_making」メソッドで初期化して渡すというよりは、要素の書き換えが発生するメソッド内だけで初期化と要素の書き換えを行うようにお願いします。

今回の課題ではそのケースはないのですが、要素の書き換えが可能なリストを触れる範囲が広いと、最初に実装した人が意図していない要素の追加や削除が行われる可能性があるからです。

2020-08-25 02:49 UTC, FTS-Yama reviewed
コメント

2020-08-25 02:49 UTC, FTS-Yama commented on src/test/java/org/docksidestage/javatry/basic/Step02IfForTest.java
> +            log(stage2List);
>"a" が含まれているものだけのリストを作成して、それをループで回してログに表示しましょう。(Stream APIなしで))

上記コメントの意図ですが、「a」の文字が含まれる文字列だけのリストを作成して、ループの中で「stage2List」を出力をするのではなく以下の仕様になります。

１．prepareStageList()のリストから「a」の文字が含まれる文字列だけのリストを作成
２．１の処理とは別でループを回し、各要素をログに出力する

2020-08-25 02:52 UTC, FTS-Yama requested changes
完了

2020-08-25 02:52 UTC, FTS-Yama approved these changes

2020-08-25 05:02 UTC, fts-tamori commented on src/test/java/org/docksidestage/javatry/basic/Step02IfForTest.java
> +        final List<String> stage2List = new ArrayList<>();
分かりました。

2020-08-25 05:15 UTC, merged